### PR TITLE
Fix for property "disable" that doesn't work anymore using Vue 2.7

### LINKED ISSUE #31: [Regression] property "disable" doesn't work anymore using vue-focus-lock 2.0.3 and Vue 2.7
Hi,
now that issue #25 is fixed, I encounter another regression using vue-focus-lock 2.0.3 and Vue 2.7

In one of my projet, I have sometimes to disable and re-enable the focus lock by doing `<Lock :disabled="disableAppFocusLock">`.
The disabling seems to work but not the re-enabling of the focus lock.

Following links pointed my to a solution:
[Calling useVuelidate from async setup function](https://github.com/vuelidate/vuelidate/blob/next/packages/docs/src/advanced_usage.md#calling-usevuelidate-from-async-setup-function)
[fix #1079 - Add support for Vue 2.7](https://github.com/vuelidate/vuelidate/pull/1082)

### PR DESCRIPTION
**Pull request by tbl0605**
Fixes  #31

### CODE REVIEW

File: src/Lock.vue [hunk 1]
```diff
@@ -148,7 +148,7 @@
       let originalFocusedElement;
 
       onMounted(() => {
-        data.value.vue = getCurrentInstance();
+        data.value.vue = (getCurrentInstance() || {}).proxy;
```
Comment (theKashey) [inline src/Lock.vue:151]: technically we don't need "real" instance of the component hidden behind non fancy name `proxy`. One can use `getCurrentInstance.uid`

But I am a little concerned about `|| {}` construct - it is possible that there is no current instance? Logic will be broken in this case.

Thinking would the following work
```tsx
data.value.vue = getCurrentInstance().uid;
```

Comment (theKashey) [reply src/Lock.vue:151]: Ok, you were right. There are all different types in 2.6, 2.7 and 3 and proxy is the only one in common
